// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZEoVa_BwCTtF16OAHqw5f67bH-11pUTQ',
    appId: '1:622742866334:android:6e99c451f1007f559c6e8f',
    messagingSenderId: '622742866334',
    projectId: 'flutter-udemy-backend-ef769',
    databaseURL: 'https://flutter-udemy-backend-ef769-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-udemy-backend-ef769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaLWZvq2P4CPNPBx6GYaCI1rYnpqmMHhI',
    appId: '1:622742866334:ios:b22d4aeff3ab1a419c6e8f',
    messagingSenderId: '622742866334',
    projectId: 'flutter-udemy-backend-ef769',
    databaseURL: 'https://flutter-udemy-backend-ef769-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-udemy-backend-ef769.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}